defaults: &defaults

  domain: "http://0.0.0.0:3000"
  fb_token: "230258430429159|t-jmyqCxomGNW5jT6K2n23HEdfE"
  hotelier_langs:
    - en
    - ru
    - ua
  currency:
    - UAH
    - EUR
    - USD
    - RUR
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  domain: "http://193.84.22.53"

staging:
  <<: *defaults
