defaults: &defaults
  email_templates:
    add_cv: "add_cv"
    school_registration: "school_registration"
    club_registration: "club_registration"
    test_results: "test_results"
    blog_subscribe: "blog_subscribe"




development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

deployment:
  <<: *defaults
